-- Schema v2: the projects/workspaces relational model (PRD-2, Phase 1).
--
-- A `project` is just a NAME with N named `workspaces`. A workspace is a single
-- absolute, NORMALIZED folder path (git-agnostic; `branch` is optional metadata).
-- Terminals gain an optional binding to a workspace plus a binding mode
-- (auto follows the live cwd; manual stays pinned until unpin).
--
-- Path normalization (case/separator/form) is done in the Rust layer BEFORE a
-- path is stored or compared (see `crate::pathnorm`), so the UNIQUE(project_id,
-- path) constraint and the auto-attach ancestor matching operate on canonical
-- strings. SQLite string comparison is byte-exact, so two spellings of the same
-- directory only collide once the backend has normalized them identically.
--
-- Timestamps mirror the `terminals` table: epoch MILLISECONDS as INTEGER, set
-- explicitly by the backend on every write, with a portable julianday DEFAULT as
-- a safety net for any raw insert.

-- A project: a name and its lifecycle timestamps. Workspaces hang off it.
--
-- `collapsed` is the persisted sidebar disclosure state (0 = open/expanded,
-- 1 = collapsed). A SQLite INTEGER 0/1 boolean (mapped to a Rust `bool`), it
-- defaults to 0 so a freshly-created project opens expanded; the sidebar reads
-- it on reload to restore each band's open/closed state.
CREATE TABLE projects (
    -- UUIDv7 generated by the backend (SQLite does not auto-generate it).
    id         TEXT    NOT NULL PRIMARY KEY,
    name       TEXT    NOT NULL,
    collapsed  INTEGER NOT NULL DEFAULT 0 CHECK (collapsed IN (0, 1)),
    created_at INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    updated_at INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER))
);

-- A workspace: a named, normalized folder belonging to exactly one project.
--
-- `path` is the canonical (Rust-normalized) absolute directory. It is NOT
-- globally unique — the same folder may legitimately appear under two different
-- projects — but it is UNIQUE WITHIN a project via UNIQUE(project_id, path).
--
-- `branch` is optional git metadata; nyx stays git-agnostic (a workspace is just
-- a folder). `is_root` flags the project's single root workspace; exactly one
-- root per project is enforced by the partial unique index below.
--
-- `collapsed` mirrors the projects column: the persisted sidebar disclosure
-- state (0 = open, 1 = collapsed), defaulting to 0 so a new workspace expands.
CREATE TABLE workspaces (
    id         TEXT    NOT NULL PRIMARY KEY,
    project_id TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name       TEXT    NOT NULL,
    path       TEXT    NOT NULL,
    branch     TEXT,
    is_root    INTEGER NOT NULL DEFAULT 0 CHECK (is_root IN (0, 1)),
    collapsed  INTEGER NOT NULL DEFAULT 0 CHECK (collapsed IN (0, 1)),
    created_at INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    updated_at INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    -- A path is unique within a project, never globally. Two projects may anchor
    -- the same folder; the same folder twice in ONE project is rejected.
    UNIQUE (project_id, path)
);

-- Exactly one root workspace per project. A PARTIAL unique index (only rows with
-- is_root=1 participate) makes "two roots in the same project" a constraint
-- violation while leaving the non-root workspaces unconstrained on this axis.
CREATE UNIQUE INDEX idx_one_root_per_project
    ON workspaces (project_id)
    WHERE is_root = 1;

-- Index the FK column for fast `list_workspaces(project_id)` and ancestor scans.
CREATE INDEX idx_workspaces_project ON workspaces (project_id);

-- Extend `terminals` with the optional workspace binding.
--
-- `workspace_id` is the workspace this terminal is attached to (NULL = none).
-- ON DELETE SET NULL: deleting a workspace detaches its terminals rather than
-- deleting the terminal records (the terminals outlive a workspace removal).
ALTER TABLE terminals
    ADD COLUMN workspace_id TEXT REFERENCES workspaces(id) ON DELETE SET NULL;

-- `workspace_binding_mode` controls auto-attach behaviour:
--   'auto'   — the terminal follows its resolved live cwd (default).
--   'manual' — the terminal stays pinned to workspace_id until unpinned.
-- Default 'auto' so existing/never-pinned terminals participate in auto-attach.
ALTER TABLE terminals
    ADD COLUMN workspace_binding_mode TEXT NOT NULL DEFAULT 'auto'
        CHECK (workspace_binding_mode IN ('auto', 'manual'));
