-- Schema v1: the `terminals` table.
--
-- First persistent table of nyx (ADR-0001: backend owns the SQLite base via
-- Diesel). One row per terminal nyx knows about. `scrollback` holds the
-- serialized xterm history (written debounced/bounded by the front, persisted
-- by the backend); `status` distinguishes a live terminal (re-spawned at launch)
-- from one closed on purpose (not re-spawned).
--
-- `"order"` is double-quoted: ORDER is a SQL keyword. The Diesel column is
-- exposed as `order_index` (see schema.rs) so Rust code never collides with the
-- `order` keyword either.
--
-- Timestamps are epoch MILLISECONDS as INTEGER (SQLite has no native datetime;
-- ms is what the front consumes as a plain JS number). The backend sets them
-- explicitly on every write; the column DEFAULTs are a safety net for any raw
-- insert. `closed_at` is NULL until the terminal is closed (status='closed').
CREATE TABLE terminals (
    -- UUIDv7 generated by the backend (SQLite does not auto-generate it).
    id         TEXT    NOT NULL PRIMARY KEY,
    cwd        TEXT    NOT NULL,
    label      TEXT,
    scrollback TEXT    NOT NULL DEFAULT '',
    status     TEXT    NOT NULL DEFAULT 'alive' CHECK (status IN ('alive', 'closed')),
    "order"    INTEGER NOT NULL DEFAULT 0,
    -- epoch ms; the (julianday - unix-epoch-julian) * ms/day form is portable
    -- across SQLite versions (no dependency on unixepoch('subsec')).
    created_at INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    updated_at INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    closed_at  INTEGER,
    -- epoch ms of the last time this terminal was the active one; the launcher
    -- reopens on the alive terminal with the greatest value (NULL = never).
    last_active_at INTEGER
);
