/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * A command-runtime event surfaced to Node (the `command://state` / `command://ack`
 * transitions, plus an output-cleared tick). The host maps `kind` to the matching
 * Tauri event name so the renderer's command band behaves identically.
 */
export interface CommandStateEvent {
  /**
   * `"state"` (a run-state transition), `"ack"` (unread cleared), or
   * `"output-cleared"` (the captured buffer was wiped).
   */
  kind: string
  /** The `command_instances.id` the event is about. */
  instanceId: string
  /** The `idle|running|success|error` string for a `"state"` event; empty otherwise. */
  state: string
  /** The natural exit code on a `success`/`error` finish; `None` otherwise. */
  exitCode?: number
}
/**
 * A coalesced command-output chunk surfaced to Node (`command://output`). Bytes are
 * delivered as a `Buffer` on the Node loop, ordered per instance.
 */
export interface CommandOutputEvent {
  /** The `command_instances.id` whose output this is. */
  instanceId: string
  /** The coalesced output bytes (raw — the renderer's xterm renders them as-is). */
  bytes: Buffer
}
/**
 * The status of a command instance after a lifecycle call, mirrored to Node — the
 * napi shape of the runner's live `outcome` (or the cold default). `running` is the
 * live flag the renderer's dot reads; `state`/`exit_code` are the factual outcome.
 */
export interface CommandStatus {
  /** The `command_instances.id`. */
  instanceId: string
  /** `idle|running|success|error`. */
  state: string
  /** Whether the instance is LIVE-running right now. */
  running: boolean
  /** The natural exit code of the last finished run, if any. */
  exitCode?: number
  /** Whether the last finished run is still an unseen result. */
  unread: boolean
  /**
   * Whether the instance was ALREADY running before a `start`/`relaunch` call
   * (`true` ⇒ a `start` was an idempotent no-op). Defaults to `false` for reads.
   */
  wasRunning: boolean
  /**
   * Whether this call RESTARTED the instance (`relaunch` ⇒ `true`, `start` ⇒
   * `false`). Defaults to `false` for reads.
   */
  restarted: boolean
}
/**
 * A terminal record surfaced to Node for the restore flow (PRD-5 task #5). A
 * snake-free subset of `nyx_core::db::Terminal` — the fields the host needs to
 * re-open a terminal and re-evaluate its exec-state at boot. napi maps this to a
 * plain JS object.
 */
export interface TerminalRow {
  /** The persistent `terminals.id` (the sidebar / event key). */
  id: string
  /** `alive` | `closed` — only `alive` terminals are re-spawned at boot. */
  status: string
  /** The terminal's last working dir (for the re-spawned shell's cwd). */
  cwd: string
  /** Optional user label. */
  label?: string
  /** Sidebar order. */
  orderIndex: number
  /** The workspace this terminal is attached to (`None` = loose). */
  workspaceId?: string
  /** `idle` | `running` | `success` | `error` — the persisted exec-state badge. */
  execState: string
  /** Settled exit code, if any. */
  execExitCode?: number
  /** Whether the settled exec-state is an unread notification. */
  execStateUnread: boolean
  /** Epoch-ms of the last exec-state transition. */
  execStateUpdatedAt: number
}
/**
 * The result of persisting an exec-state transition (PRD-5 task #1): the stamped
 * `exec_state_updated_at` so the host's `terminal://exec-state` event carries the
 * exact persisted timestamp (parity with the Tauri `persist_and_emit_exec_state`).
 * `updated` is `false` when the terminal id was unknown (no row updated) — the host
 * then SKIPS the emit, never announcing a state the DB does not hold.
 */
export interface ExecStatePersist {
  /** Whether a row was actually updated (the terminal id exists). */
  updated: boolean
  /** The stamped `exec_state_updated_at` (epoch-ms); `0` when `updated` is false. */
  updatedAt: number
}
/**
 * One terminal's RUNTIME agent activity, surfaced to the front (the live dot). Mirrors
 * `nyx_core::agent_activity::ActivitySnapshot`, with the [`Activity`] enum flattened to
 * a string the front maps to the dot: `"working"` (running blue) | `"waiting"`
 * (attention) | `"idle"`. `ready_unread` is the focus-aware "response ready" green-dot
 * notification (cleared on focus, exactly like `exec_state_unread`). Built off the
 * in-memory store — NEVER persisted.
 */
export interface AgentActivitySnapshot {
  /** The terminal record id this activity belongs to. */
  terminalId: string
  /** `working` | `waiting` | `idle` — the stored activity kind (no time-based expiry). */
  activity: string
  /** `true` when a turn finished and the user has not yet viewed the terminal. */
  readyUnread: boolean
  /**
   * The RED analogue of `ready_unread` — `true` when the last turn ended on an API error
   * (`StopFailure`) and the user has not yet viewed the terminal (#35). Cleared on focus
   * (mark-read), a new turn, and PTY death / SessionEnd / close. Exposed to JS as
   * `errorUnread`.
   */
  errorUnread: boolean
  /**
   * `true` when the plugin THIS session loaded is OLDER/different than the version nyx
   * bundles (#18b) — the per-session "plugin périmé" badge inviting a session restart.
   * Set once at SessionStart, runtime-only (never persisted), cleared on PTY death /
   * SessionEnd / close (a restarted session starts not outdated).
   */
  pluginOutdated: boolean
}
/**
 * The result of an auto-attach pass surfaced to Node (the `auto_attach_terminal` command
 * result) — mirrors `nyx_core::resolve::AutoAttachResult`. The front reflects the new
 * binding ONLY when `changed`, so it never silently un-pins a manual terminal.
 */
export interface AutoAttachResultJs {
  /** The workspace the terminal is bound to after the pass (`null` = loose). */
  workspaceId?: string
  /** Whether the binding actually changed. */
  changed: boolean
}
/**
 * A parked agent-session resume (PRD-5 task #5). The host stashes these keyed by
 * `terminalId` at boot and INJECTS `command` (`claude --resume <id>`, CR-terminated) when that
 * terminal's PTY next spawns — the napi mirror of the Tauri `PendingResumes` +
 * `register_terminal_pty` injection.
 */
export interface ResumePark {
  /** The persistent terminal record id whose first respawn should inject the resume. */
  terminalId: string
  /** The exact line to inject (e.g. `claude --resume <external_session_id>`). */
  command: string
  /** The `agent_sessions.id` — so a failed injection can mark it `resume_failed`. */
  sessionId: string
  /** Whether the resume is UNCERTAIN (best-effort; surfaced for parity/diagnostics). */
  uncertain: boolean
}
/**
 * A coarse `changed` invalidation surfaced to Node so the host emits its
 * `*://changed` event and the renderer re-pulls (mirrors `nyx_core::frontier::ChangedTopic`).
 */
export interface McpChangedEvent {
  /** `terminals` | `workspaces` | `commands` | `agent-sessions`. */
  topic: string
}
/**
 * A LIVE-PTY terminal operation an MCP terminal tool needs the host's Node PTY manager
 * to perform (the half `nyx-core` cannot do — it owns the records, not the live PTY).
 * Delivered to Node fire-and-forget; the renderer-owned PTY reconciliation does the work.
 */
export interface McpTerminalOp {
  /**
   * `park` (a `create_terminal` opening command) | `send` (a `send_to_terminal` write,
   * the host appends ``) | `send_raw` (a `send_keys` write of RAW pre-resolved bytes,
   * the host appends NOTHING) | `close` (kill the terminal's PTY).
   */
  op: string
  /** The terminal RECORD id the op targets. */
  terminalId: string
  /**
   * The payload: the command LINE for `park`/`send` (the host appends ``); the RAW
   * bytes HEX-ENCODED for `send_raw` (the host decodes `Buffer.from(command, "hex")` and
   * writes them verbatim, NO newline); empty for `close`. Hex keeps arbitrary control
   * bytes intact across the Node boundary without a base64 dependency or a lossy string
   * round-trip.
   */
  command: string
}
/**
 * The nyx-core version string this native addon was built against. The Electron
 * core-host calls this right after loading the `.node` as a liveness + ABI-match
 * probe (if the addon loaded under the wrong ABI it would fail to load at all, so
 * a successful `version()` call proves the ABI matches the host Electron).
 */
export declare function version(): string
/**
 * A decoded exec-state transition surfaced to Node (PRD-2.1, OSC 133). At parity
 * with the Tauri bridge's `drive_exec_state`: only a command END produces a
 * transition — a `D;0` is `success`, any other code (or a missing one) is `error`.
 * `running` is NOT driven from OSC 133 (the OS busy signal owns it); the
 * pre-exec/prompt markers are inert. The host maps this onto `terminal://exec-state`
 * and (phase 5) the DB record. `state` is `"success"` or `"error"`.
 */
export interface ExecStateEvent {
  /** `"success"` (exit 0) or `"error"` (non-zero / unknown). */
  state: string
  /**
   * The exit code when the `D` carried a parseable one; `None` otherwise (still
   * `error`-colored — finished but unknown).
   */
  exitCode?: number
}
/**
 * The live auto-label introspection of a terminal (the `terminal_info` command result),
 * at parity with the Tauri bridge's `TerminalInfo`. Both fields are `null` on a platform
 * without `/proc` (Windows) — a clean degradation, never an error.
 */
export interface TerminalInfo {
  /**
   * The shell's LIVE working directory (`readlink /proc/<shell_pid>/cwd`), or `null`
   * when it cannot be read (process gone, no `/proc`).
   */
  cwd?: string
  /**
   * The foreground program name (`/proc/<foreground_pgid>/comm`) — `htop` while a
   * program runs, the shell name at an idle prompt, `null` when undeterminable.
   */
  foreground?: string
}
/**
 * One terminal's process-tree resource usage (FEEDBACK #28), at the napi frontier:
 * the summed CPU% + resident memory of the shell AND all its transitive descendants.
 * Mirrors `nyx_core::proc_stats::TreeStats`.
 */
export interface TreeStats {
  /**
   * Summed CPU usage of the tree, in PERCENT (relative to a single core, so a tree
   * busy on N cores can exceed 100 — e.g. a parallel build). The host/UI may clamp.
   */
  cpuPct: number
  /**
   * Summed resident memory of the tree, in BYTES (RSS). A JS `number` holds this
   * exactly up to 2^53 bytes (8 PiB), far beyond any real terminal's footprint.
   */
  memBytes: number
}
/**
 * The managed-command runner the Electron core-host owns (parity with the Tauri
 * `ManagedCommandRunner`). Built once at boot over the SHARED pool + the Node event
 * callbacks; drives the off-screen command PTYs.
 */
export declare class NyxCommandRunner {
  /**
   * Start an instance (idempotent on an already-running one — the no-double-spawn
   * guard lives at the runner boundary). Resolves the command line + cwd from the DB
   * (validated subfolder) BEFORE spawning, so an unknown instance / bad subfolder is
   * a readable error and never a half-spawn. Returns the status with `was_running`
   * (the call was a no-op) and `restarted:false` (a start is never a restart).
   */
  start(instanceId: string): CommandStatus
  /**
   * Stop a running instance (tree-kill of the whole process group). Idempotent on a
   * non-running instance (returns the current status, never an error). `was_running`
   * reports liveness BEFORE the stop.
   */
  stop(instanceId: string): CommandStatus
  /**
   * Relaunch (the EXPLICIT restart — stop-then-start if running, else a direct
   * start; never leaves two live processes). Resolves command + cwd like `start`.
   * `restarted:true`; `was_running` reports whether a live process was stopped first.
   */
  relaunch(instanceId: string): CommandStatus
  /**
   * Read an instance's captured output: the runner's LIVE in-memory tail while
   * running, else the persisted scrollback rehydrated from the DB (the SAME source
   * precedence as `bridge::command_output`). Unknown instance → a readable error.
   */
  getOutput(instanceId: string): string
  /**
   * The live run status of an instance (no mutation) — the runner outcome or the
   * cold default. Used by the host / MCP `get_command_output` status block.
   */
  status(instanceId: string): CommandStatus
  /** Whether the instance currently has a LIVE running process in the runner. */
  isRunning(instanceId: string): boolean
  /**
   * Acknowledge a FINISHED one-shot's "unseen result" (parity with the Tauri
   * `command_acknowledge` / `acknowledge_unread`): clear ONLY its `unread` flag and
   * emit `command://ack`, NEVER its factual outcome. Two paths, both clearing only the
   * unread flag:
   *   - LIVE entry (a run that finished this session): the runner flips its in-memory
   *     `unread` and (via the sink) persists `unread=0` + emits `command://ack`;
   *   - PERSISTED-only state (no live entry, e.g. a success/error restored at boot):
   *     clear the persisted `unread` here and emit `command://ack` via the sink — so a
   *     restored, still-unread badge also hides on select.
   *
   * A `running` instance is never acknowledged (no unseen result yet). Returns the
   * FACTUAL `last_state` string after the call (unchanged by the ack). Unknown id → a
   * readable error.
   */
  acknowledge(instanceId: string): string
  /**
   * BOOT RESTORE (parity with the Tauri `setup`): relaunch every instance whose
   * template `restart_on_startup` is ON and whose `was_running_on_shutdown` snapshot
   * is true, normalize any orphaned persisted-`running` to idle, and reset the
   * snapshots. Returns the relaunched instance ids. Drives the SHELL-AGNOSTIC
   * `nyx_core::command::restore_commands_on_boot` (the identical code the Tauri
   * adapter delegates to).
   */
  restoreOnBoot(): Array<string>
  /**
   * SHUTDOWN SNAPSHOT (parity with the Tauri close hook): for every instance persist
   * `was_running_on_shutdown = is_running`. Drives the shell-agnostic
   * `nyx_core::command::snapshot_commands_on_shutdown`. Idempotent under the
   * `begin_shutdown` latch (call it before `kill_all_running`).
   */
  snapshotOnShutdown(): void
  /**
   * Latch the shutdown so the snapshot+reap run EXACTLY once (the close-request +
   * destroy double-event guard). Returns `true` only the first time.
   */
  beginShutdown(): boolean
  /**
   * Hard-kill EVERY running instance's process tree on shutdown so a managed command
   * (its shell + child dev server + the Windows conhost) is REAPED, never orphaned.
   * Best-effort + non-blocking.
   */
  killAllRunning(): void
}
/**
 * The napi handle the core-host owns over shared nyx-core state. Created once at boot
 * (`NyxCore::open(dataDir)`); every DB method returns an `AsyncTask` (a `Promise` in
 * JS) so the query runs on a libuv worker, never the Node loop.
 */
export declare class NyxCore {
  /**
   * Open (creating if absent) the SQLite DB under `data_dir` and build the shared
   * r2d2 pool (WAL + foreign_keys + busy_timeout per connection). Migrations run
   * once here. A failure (bad path / migration error) throws a readable error the
   * host turns into a fatal boot state — never a silent hang.
   *
   * `data_dir` must already exist (main creates `userData`); the DB file is
   * `data_dir/nyx.db`, the SAME name + location convention as the Tauri shell.
   */
  constructor(dataDir: string)
  /**
   * Build the managed-command runner over Node event callbacks + the SHARED pool,
   * stash its `Arc<CommandRunner>` so the MCP dispatcher can route the runtime
   * command tools onto it, and return the [`NyxCommandRunner`] handle the host owns.
   *
   * Idempotent-ish: a second call rebuilds the runner (the host builds it exactly
   * once at boot). The two callbacks are the `command://state`+`ack`+`output-cleared`
   * sink and the `command://output` sink — delivered on the Node loop, mapped by the
   * host to the Tauri event names so the renderer's command band is at parity.
   */
  createCommandRunner(onState: (err: null | Error, ev: CommandStateEvent) => void, onOutput: (err: null | Error, ev: CommandOutputEvent) => void): NyxCommandRunner
  /**
   * Publish the record↔live-PTY join into the SYNCHRONOUS liveness registry (the
   * `register_terminal_pty` command — the Electron mirror of the Tauri `TerminalPtyMap`
   * set). The front calls this once its `<Terminal>` has spawned the PTY for `record_id`,
   * binding the durable record id to the live `pty_id`. After this, the MCP terminal
   * tools resolve the record to a LIVE shell synchronously: `send_to_terminal` writes
   * (instead of `invalid_state`), and `list_terminals` reports `live: true`. Idempotent —
   * re-registering the same record overwrites with the latest pty id.
   */
  registerTerminalPty(recordId: string, ptyId: number): void
  /**
   * Retract the record↔live-PTY join (the `register_terminal_pty` command with a null
   * pty, and the PTY-exit cleanup). The record's shell is no longer live, so the MCP
   * terminal tools fall back to `invalid_state` for `send_to_terminal` and `live: false`
   * for `list_terminals` — exactly the Tauri `TerminalPtyMap::clear` behaviour. Idempotent.
   */
  unregisterTerminalPty(recordId: string): void
  /**
   * Snapshot the RUNTIME agent activity of every terminal with something LIVE to show
   * (working/waiting OR a pending "ready" notification). Synchronous — a cheap
   * in-memory map read, never the Node loop / never the DB. The host calls this on the
   * `agent-sessions` change tick and at mount to build the live-dot map for the
   * renderer. A terminal that is idle (or whose `working` has gone stale) with no
   * pending ready is omitted (the front treats absence as idle).
   */
  agentActivitySnapshot(): Array<AgentActivitySnapshot>
  /**
   * FORCE a terminal's runtime activity to idle and drop its "ready" notification — the
   * anti-phantom clear the host calls on PTY death / terminal close (the agent-activity
   * analogue of "emit busy=false on PTY death"). Synchronous, idempotent. A killed
   * Claude that never sent `Stop` cannot leave a phantom running dot after this.
   */
  clearAgentActivity(terminalId: string): void
  /**
   * Clear ONLY the focus-aware "response ready" notification for a terminal (the
   * activity mark-read), leaving any live `working` activity intact. Called when the
   * user VIEWS the terminal — the same focus-aware clear as `terminal_exec_mark_read`.
   * Synchronous, idempotent.
   */
  markAgentReadyRead(terminalId: string): void
  /**
   * Auto-attach a terminal RECORD to a workspace by its live `cwd`, off the Node loop
   * (the `auto_attach_terminal` command). Runs the SHARED nyx-core resolver body at
   * Tauri parity; resolves to `{ workspaceId, changed }`.
   */
  autoAttachTerminal(terminalId: string, cwd?: string | undefined | null): Promise<AutoAttachResultJs>
  /**
   * Persist a terminal exec-state transition (OSC 133 result annotation) off the
   * Node loop. Resolves to `{ updated, updatedAt }` so the host emits
   * `terminal://exec-state` with the exact persisted timestamp, and skips the emit
   * when `updated` is false (unknown id). Mirrors `persist_and_emit_exec_state`.
   */
  setExecState(terminalId: string, state: string, exitCode: number | undefined | null, unread: boolean): Promise<ExecStatePersist>
  /**
   * Read a terminal record (so the host can settle a stale `running` to idle on PTY
   * exit). Resolves to the row or `null`.
   */
  getTerminal(terminalId: string): Promise<TerminalRow | null>
  /**
   * List every terminal in sidebar order (the boot restore read). Resolves to the
   * rows.
   */
  listTerminals(): Promise<Array<TerminalRow>>
  /**
   * Create a new alive terminal record (the host persists it so restore can re-open
   * it). Resolves to the created row.
   */
  createTerminal(cwd: string, label?: string | undefined | null): Promise<TerminalRow>
  /**
   * Settle every terminal stuck at a persisted `running` down to idle (boot
   * normalization). Resolves to the count normalized.
   */
  normalizePhantomTerminals(): Promise<number>
  /**
   * BOOT agent-session RESUME scan (PRD-5 task #5): sweep stale sessions, gather
   * resumable candidates, and return the `claude --resume` parks to inject at each
   * eligible terminal's first respawn. Resolves to the parks.
   */
  resumeScanOnBoot(): Promise<Array<ResumePark>>
  /**
   * Mark an agent session `resume_failed` (PRD-5 task #5) when a parked resume could
   * not be injected (PTY gone / write failed), so the next launch won't retry.
   */
  markResumeFailed(sessionId: string): Promise<void>
  /**
   * TEST/PROOF ONLY: run a deliberately slow DB query (`delay_ms`) on a libuv worker
   * to demonstrate it does NOT block the Node loop or PTY output. Resolves to the
   * terminal count once the stall elapses.
   */
  dbSlowQuery(delayMs: number): Promise<number>
  /**
   * The GENERIC, allowlisted DB-command dispatcher (PRD-5 review — full nyxBridge
   * surface end-to-end). The Electron core-host forwards the contract's
   * `BackendCommand` NAME + a JSON args STRING here; the task dispatches to the SAME
   * `nyx_core::db` CRUD the Tauri bridge calls and resolves a JSON RESULT STRING (the
   * host `JSON.parse`s it back to the contract shape). Runs on a libuv worker (off the
   * Node loop), so even a slow query never blocks IPC or PTY output — the SAME
   * non-blocking guarantee as every other DB task. An unknown command, or one not
   * available over this transport, rejects with a readable error.
   *
   * `args_json` MUST be a JSON object (`"{}"` for the no-arg commands); a malformed
   * blob is a readable parse error, never a panic.
   */
  dbCommand(command: string, argsJson: string): Promise<string>
  /**
   * Start the MCP server (idempotent — start-once, ADR-0003 D3), installing the
   * pool-backed dispatcher so `tools/call` resolves the FULL advertised surface from
   * the SHARED pool + the managed runner + the host's Node PTY bridge. Returns the
   * bound port. A bind failure (port taken) throws a readable error the host logs as a
   * warning — it must NOT be a hard boot failure.
   *
   * `on_changed` (optional) receives a coarse `changed` invalidation after a mutating
   * tool so the renderer re-pulls; `on_terminal_op` (optional) receives the live-PTY
   * operations the terminal tools queue to the host's PTY manager. A bare/headless
   * start may omit both (the mutations still commit; nothing is pushed to a front).
   */
  mcpStart(onChanged?: (err: null | Error, ev: McpChangedEvent) => void, onTerminalOp?: (err: null | Error, op: McpTerminalOp) => void): number
  /** The port the MCP server bound, or 0 if not started. */
  mcpPort(): number
  /** Whether the MCP server has been started (latched). */
  mcpIsStarted(): boolean
  /**
   * Boot reconciliation (PRD-5 task #4, parity with the Tauri `setup`): for every
   * provider the user has explicitly installed, re-template/re-register its bundled
   * plugin and propagate version bumps — but NEVER install on boot. Runs DETACHED on
   * its own thread; best-effort. `data_dir` is the integrations-state dir;
   * `resource_dir` (or `null`) lets a packaged build resolve the bundled plugin.
   */
  mcpReconcile(dataDir: string, resourceDir?: string | undefined | null): void
}
/**
 * The full interactive PTY exposed to Node. One instance == one shell in a PTY.
 * Spawn it with output/exit/cwd/exec-state callbacks; drive it with
 * write/resize/kill/setPaused. The host keys these by terminal id (the live
 * `pty_id → record id` map stays on the JS side, exactly like the Tauri
 * `TerminalIdMap`), so this class carries no multi-terminal registry itself.
 */
export declare class NyxPty {
  /**
   * Spawn the default shell in a `cols`x`rows` PTY and stream it to Node.
   *
   * - `cwd`: working dir for the shell (`None`/`undefined` → the host's cwd).
   * - `terminal_id`: nyx's PERSISTENT terminal record id, exported into the shell
   *   as `NYX_TERMINAL_ID` for agent-session correlation (PRD-5 task #3). `None`
   *   for a record-less terminal.
   * - `on_data`: each coalesced output chunk, as a `Buffer`, on the Node loop.
   * - `on_exit`: fired once when the shell exits, with the exit code (or `null`).
   * - `on_cwd`: the decoded OSC 7 cwd whenever the shell reports one (most-recent
   *   per chunk). Lets auto-attach work portably (Windows/macOS have no `/proc`).
   * - `on_exec_state`: a decoded OSC 133 command-END transition (success/error).
   *
   * The OSC callbacks are PURELY OBSERVATIONAL: the control bytes still flow to
   * `on_data` (xterm renders the full stream); we never strip them.
   */
  constructor(cols: number, rows: number, cwd: string | undefined | null, terminalId: string | undefined | null, onData: (err: null | Error, bytes: Buffer) => void, onExit: (err: null | Error, code: number | null) => void, onCwd: (err: null | Error, cwd: string) => void, onExecState: (err: null | Error, ev: ExecStateEvent) => void)
  /**
   * Write bytes (keystrokes / paste) to the PTY. Flushes immediately so echo is
   * not buffered.
   */
  write(data: Buffer): void
  /**
   * Resize the PTY window (delivers SIGWINCH to the child). Idempotent — a resize
   * to the current size is a harmless no-op. Pixel dims are best-effort (0 here).
   */
  resize(cols: number, rows: number): void
  /**
   * Terminate the child shell. Idempotent: killing an already-dead child is a
   * no-op. After this the reader EOFs, the pump flushes its tail and fires
   * `on_exit`.
   */
  kill(): void
  /**
   * LOSSLESS FLOW CONTROL (PRD frozen decision / annexe §E). Pause or resume the
   * reader thread. Paused → the core reader blocks at its gate, the kernel PTY
   * buffer fills, and the child blocks on write (real OS backpressure — nothing
   * is dropped or reordered). The host calls `setPaused(true)` when the renderer's
   * xterm-acknowledged backlog crosses the high-water mark and `setPaused(false)`
   * when it drains below the low-water mark.
   */
  setPaused(paused: boolean): void
  /** The live PTY id (so the host can correlate streams in the multi-terminal case). */
  id(): number
  /**
   * The OS-derived BUSY bit (PRD-5 task #1 / decision 1-B): `Some(true)` when a
   * command runs in this PTY's foreground (`foreground_pgid != shell pgid`),
   * `Some(false)` at an idle prompt, `None` when the signal cannot be derived
   * (non-Unix — ConPTY has no `tcgetpgrp` — or the master is already closed).
   *
   * This is the AUTHORITY for the running dot, read by the host's busy-state poll
   * loop — the SAME `Pty::is_busy` derivation the Tauri bridge polls, exposed here
   * so the Electron core-host can re-host the `start_busy_state_loop` over napi at
   * parity. It is INDEPENDENT of OSC 133 (a force-quit/restore can never leave a
   * phantom running: a restored terminal with no foreground command samples idle by
   * construction). One cheap `tcgetpgrp` per call; the host polls on a bounded
   * cadence and emits `terminal://busy-state` only on a TRANSITION.
   */
  busy(): boolean | null
  /**
   * This terminal's ROOT pid — the shell process id, the anchor of its process tree
   * (FEEDBACK #28). The host's per-terminal stats poll passes this to
   * `NyxProcStats.treeStats` to sum the shell + all descendants' CPU%/RAM. `None`
   * when the shell pid is unknown (a spawn that did not yield a pid). Portable: every
   * OS exposes the child's pid.
   */
  shellPid(): number | null
  /**
   * The LIVE auto-label introspection of this terminal (the `terminal_info` command's
   * backend — PRD-5 auto-label / auto-attach revival): a fresh `{ cwd, foreground }`
   * read straight from the kernel, NOT from OSC 7. Anchored on the live PTY:
   *  - `cwd` is `readlink /proc/<shell_pid>/cwd` — the shell's real cwd, reflecting
   *    every `cd` the user typed, instantly;
   *  - `foreground` is `/proc/<foreground_pgid>/comm` — the program currently in the
   *    PTY's foreground (`htop`/`vim`), or the shell name at an idle prompt.
   *
   * Both come from `nyx_core::proc`, keyed by the SAME `shell_pid` / `foreground_pgid`
   * the Tauri `terminal_info` uses (parity). On a platform without `/proc` (Windows —
   * no `/proc`, no `tcgetpgrp`) both fields are `null` WITHOUT erroring: a clean
   * degradation (the front's auto-label simply yields no live label), never an error
   * the per-second poll would spam. The host polls this on a bounded ~1s cadence
   * (the front debounces), so it is two cheap syscalls, never per output byte.
   */
  terminalInfo(): TerminalInfo
}
/**
 * Cross-platform per-terminal CPU%/RAM introspector (FEEDBACK #28). Owns ONE live
 * `sysinfo::System` kept ALIVE across calls so per-process CPU% deltas are meaningful
 * (a fresh System per call would always read 0% — see `nyx_core::proc_stats`). The
 * host builds exactly ONE of these at boot and calls [`tree_stats_batch`](Self::tree_stats_batch)
 * ONCE per poll tick with EVERY live terminal's shell pid.
 *
 * ## Off the Node main thread (FEEDBACK #28 perf)
 *
 * The full `/proc` scan is EXPENSIVE; with N terminals the old `tree_stats`-per-terminal
 * loop ran N full scans SYNCHRONOUSLY on the Node main thread, blocking the event loop for
 * hundreds of ms and freezing keystroke IPC. So the live `ProcStats` (the one `System`) now
 * lives behind an `Arc<Mutex<…>>`, and [`tree_stats_batch`](Self::tree_stats_batch) returns
 * an [`AsyncTask`]: the scan runs in `compute()` on a libuv WORKER thread (mirroring the DB
 * tasks in `core_db.rs`), never the main loop. The single `System` is preserved for CPU%
 * deltas — it is just shared through the mutex now (only the poll touches it, so there is
 * no contention).
 *
 * Cross-platform via `sysinfo` (Linux/macOS/Windows) — the descendant set is found by
 * walking PARENT pids, the one portable signal, never `/proc` session ids.
 */
export declare class NyxProcStats {
  /**
   * Build the introspector. CPU% is meaningful from the SECOND `treeStats*` call for a
   * given pid on (the first has no prior sample to diff — it reads ~0%).
   */
  constructor()
  /**
   * Refresh the process table and return the summed CPU%/RAM of the tree rooted at
   * `root_pid` (a terminal's shell pid). A pid that is GONE (the shell exited) yields
   * the all-zero reading — NEVER an error.
   *
   * SYNCHRONOUS, kept for parity/single-pid callers; the host's per-tick poll uses the
   * ASYNC [`tree_stats_batch`](Self::tree_stats_batch) so the scan never blocks the loop.
   */
  treeStats(rootPid: number): TreeStats
  /**
   * Refresh the process table ONCE, then return the summed CPU%/RAM of the tree rooted
   * at EACH pid in `roots`, one [`TreeStats`] per root IN THE SAME ORDER — OFF the Node
   * main thread (FEEDBACK #28 perf).
   *
   * The host calls this ONCE per poll tick with every live terminal's shell pid. The
   * expensive `/proc` scan happens EXACTLY ONCE per tick (not once per terminal) and on
   * a libuv WORKER thread (the returned [`AsyncTask`] is a `Promise` in JS), so the Node
   * event loop keeps servicing keystroke IPC + PTY output while the scan is in flight.
   */
  treeStatsBatch(roots: Array<number>): Promise<TreeStats[]>
}
