-- Schema v7: the GENERIC agent-session model (PRD-5, Phase 1 — ADR-0010).
--
-- nyx treats agent resume as a GENERIC problem: every terminal can host an agent
-- session that carries an EXTERNAL session id and an agent-specific resume command.
-- This table is the common substrate for ALL agents (Claude Code, Codex, OpenCode,
-- custom) even though v1 only puts the `claude_code` adapter into production.
--
-- KEY decisions baked here (mirroring the PRD Impl Decisions / ADR-0010):
--   * No `claude_session_id` (or any agent-specific column) on `terminals` — a
--     terminal references its sessions ONLY through `agent_sessions.terminal_id`.
--   * Anchor is `workspace_id` ONLY — there is NO denormalized `project_id`. The
--     project is derived via the workspace (a workspace belongs to a project,
--     PRD-2); "sessions by project" is a JOIN, not a column.
--   * `metadata_json` is a per-session JSON bag for adapter-specific details (e.g.
--     `claude_code` stores at least `source` = startup|resume|clear). The
--     STRUCTURING fields (external id, cwd, state, timestamps) stay first-class
--     columns; nothing in the common layer requires a `metadata_json` key.
--   * At most ONE `active` session per `(terminal_id, agent_kind)` — enforced by a
--     PARTIAL unique index (only `state = 'active'` rows participate), so a terminal
--     can keep many historical rows but only a single live session per agent.
--
-- Timestamps mirror the rest of the schema: epoch MILLISECONDS as INTEGER, set
-- explicitly by the Rust layer on every write, with a portable julianday DEFAULT
-- as a safety net for any raw insert.
CREATE TABLE agent_sessions (
    -- UUIDv7 generated by the backend (SQLite does not auto-generate it).
    id                  TEXT    NOT NULL PRIMARY KEY,

    -- The terminal hosting this session. ON DELETE CASCADE: removing a terminal
    -- removes its sessions (a session has no meaning without its terminal).
    terminal_id         TEXT    NOT NULL REFERENCES terminals(id) ON DELETE CASCADE,

    -- Optional workspace anchor (NULL = terminal not attached to a workspace, e.g.
    -- a loose terminal with no project). ON DELETE SET NULL: deleting a workspace
    -- detaches the session rather than deleting it (mirrors terminals.workspace_id).
    -- The project is DERIVED via this workspace; there is intentionally no
    -- project_id column.
    workspace_id        TEXT    REFERENCES workspaces(id) ON DELETE SET NULL,

    -- Which agent this session belongs to. CHECK-enforced to the v1 vocabulary;
    -- only `claude_code` is put into production by this PRD, the rest are
    -- representable for future adapters (Codex/OpenCode are spikes of PRD-6).
    agent_kind          TEXT    NOT NULL
        CHECK (agent_kind IN ('claude_code', 'codex', 'opencode', 'custom')),

    -- The agent's OWN session id (e.g. Claude's `session_id`). This is what the
    -- resume command is built from. NOT NULL: a captured session always has one.
    external_session_id TEXT    NOT NULL,

    -- The working directory the session was captured in. First-class because the
    -- resume flow and "two sessions in the same cwd" disambiguation rely on it.
    cwd                 TEXT    NOT NULL,

    -- Normalized lifecycle state (CHECK-enforced):
    --   active        — in progress, or left as-is after an app kill (still a
    --                   resume candidate; the authority is SQLite, not SessionEnd).
    --   ended         — a clean SessionEnd was observed.
    --   resume_failed — a resume was attempted but failed.
    --   unknown       — was `active` but `last_seen_at` exceeded the staleness
    --                   threshold without a clean SessionEnd (probable kill, state
    --                   unconfirmed). Still a resume candidate, but flags the doubt.
    state               TEXT    NOT NULL DEFAULT 'active'
        CHECK (state IN ('active', 'ended', 'unknown', 'resume_failed')),

    -- Optional path to the agent's transcript (e.g. Claude's `<id>.jsonl`).
    transcript_path     TEXT,

    -- Adapter-specific JSON bag (default '{}'). No key is required at the common
    -- level; `claude_code` stores at least `source` here.
    metadata_json       TEXT    NOT NULL DEFAULT '{}',

    started_at          INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),

    -- NULL until the session ends (clean SessionEnd) — like terminals.closed_at.
    ended_at            INTEGER,

    -- Refreshed on every SessionStart event. The staleness probe compares this
    -- against a threshold to flip a long-silent `active` row to `unknown`.
    last_seen_at        INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER))
);

-- At most ONE active session per (terminal_id, agent_kind). A PARTIAL unique index
-- (only state='active' rows participate) makes a second active session for the same
-- terminal+agent a constraint violation, while leaving ended/unknown/resume_failed
-- history rows unconstrained on this axis.
CREATE UNIQUE INDEX idx_one_active_session_per_terminal_agent
    ON agent_sessions (terminal_id, agent_kind)
    WHERE state = 'active';

-- Index the terminal FK for fast "sessions of this terminal" lookups + the live
-- active-session resolution.
CREATE INDEX idx_agent_sessions_terminal ON agent_sessions (terminal_id);

-- Index the workspace FK for the project-derivation join ("sessions by project").
CREATE INDEX idx_agent_sessions_workspace ON agent_sessions (workspace_id);
