// @generated automatically by Diesel CLI — kept in sync by hand here because the
// project builds without the `diesel` CLI installed. It MUST stay consistent
// with the SQL migrations under `migrations/`; the test
// `db::tests::schema_matches_migration` round-trips every column to enforce that.
//
// Mapping notes:
// - `id` is a UUIDv7 stored as SQLite `TEXT PRIMARY KEY` → `Text` (generated by
//   the backend on insert; SQLite does not auto-generate it).
// - `order` is a SQL keyword; the SQL column is `"order"` and we expose it to
//   Rust as `order_index` via `#[sql_name]` so neither SQL nor Rust collides
//   with the keyword.
// - timestamps are epoch MILLISECONDS as `INTEGER` (SQLite has no native
//   datetime) → `BigInt` (i64). `created_at`/`updated_at` are NOT NULL;
//   `closed_at` is `Nullable<BigInt>` (NULL until the terminal is closed).
// - v2 (PRD-2) added `projects`, `workspaces`, and the `terminals.workspace_id`
//   / `terminals.workspace_binding_mode` columns. `is_root` and `collapsed` are
//   SQLite INTEGER booleans (0/1) mapped as Diesel `Bool` ↔ Rust `bool`.
//   `collapsed` (on both `projects` and `workspaces`) is the persisted sidebar
//   open/closed disclosure state (0 = open). Column ORDER here must match the SQL
//   migration exactly (Diesel's positional `Queryable` decoding relies on it).
// - v3 (PRD-3) added `managed_commands` (per-project command templates, with
//   optional package.json provenance) and `command_instances` (one materialized
//   instance per template per workspace, carrying run state + scrollback +
//   shutdown snapshot). `restart_on_startup` / `was_running_on_shutdown` are
//   SQLite INTEGER 0/1 booleans mapped as Diesel `Bool` ↔ Rust `bool`. The
//   `managed_commands."order"` keyword column is exposed as `order_index` like
//   `terminals`. `source_*` / `package_manager` are nullable provenance metadata.
// - v4 (PRD-2.1) added the `terminals` exec-state columns: `exec_state` (TEXT,
//   idle|running|success|error CHECK), `exec_exit_code` (Nullable<Integer>),
//   `exec_state_unread` (SQLite 0/1 INTEGER boolean ↔ Diesel `Bool`), and
//   `exec_state_updated_at` (epoch ms `BigInt`). Appended after
//   `workspace_binding_mode`; column ORDER must match the SQL migration.
// - v4 (PRD-4) split a command instance's FACTUAL run outcome from its
//   notification/ack state on `command_instances`: `last_exit_code`
//   (Nullable<Integer>) + `ended_at` (Nullable<BigInt>) persist the last completed
//   run's natural exit code and finish time (the outcome an ack must NEVER erase),
//   and `unread` (SQLite INTEGER 0/1 boolean ↔ Diesel `Bool`) is the separate
//   "unseen result" flag a UI acknowledge clears WITHOUT collapsing the outcome.
//   All three are appended last (Diesel positional decoding) and back-fill safely
//   (unread defaults 0; the nullable columns default NULL).
// - v5 (PRD-4 dogfood review) retains the LAST completed run across a (re)launch on
//   `command_instances`: `prev_scrollback` (Text, default '') holds the prior run's
//   bounded scrollback tail, and `prev_exit_code` (Nullable<Integer>) /
//   `prev_ended_at` (Nullable<BigInt>) / `prev_last_state` (Nullable<Text>, CHECKed
//   success|error) carry its factual outcome. Bounded to ONE prior run (N=1). All
//   four are appended last (positional decoding) and back-fill safely ('' / NULL).
// - v7 (PRD-5) added `agent_sessions` (the GENERIC agent-session model, ADR-0010):
//   one row per captured agent session, anchored to a `terminal_id` (CASCADE) and an
//   OPTIONAL `workspace_id` (SET NULL) — the project is derived via the workspace, so
//   there is NO `project_id` column and NO agent-specific column on `terminals`.
//   `agent_kind` / `state` are TEXT with CHECK vocabularies (claude_code|codex|
//   opencode|custom ; active|ended|unknown|resume_failed). `external_session_id` /
//   `cwd` are first-class NOT NULL columns; `transcript_path` / `ended_at` are
//   nullable; `metadata_json` is a NOT NULL adapter JSON bag (default '{}');
//   `started_at` / `last_seen_at` are epoch-ms `BigInt`. Column ORDER here must match
//   the SQL migration exactly (Diesel positional decoding).
// - v8 (PRD-5 Phase 3) added `projects.resume_agent_sessions`: the per-project,
//   default-OFF opt-in to RESUME an active agent session at relaunch (e.g. inject
//   `claude --resume <id>` into the respawned shell). A SQLite INTEGER 0/1 boolean ↔
//   Diesel `Bool`, appended LAST on `projects` (positional decoding) and back-filling
//   safely (DEFAULT 0 → OFF for old projects — no surprise resume on upgrade).

diesel::table! {
    terminals (id) {
        id -> Text,
        cwd -> Text,
        label -> Nullable<Text>,
        scrollback -> Text,
        status -> Text,
        #[sql_name = "order"]
        order_index -> Integer,
        created_at -> BigInt,
        updated_at -> BigInt,
        closed_at -> Nullable<BigInt>,
        last_active_at -> Nullable<BigInt>,
        workspace_id -> Nullable<Text>,
        workspace_binding_mode -> Text,
        exec_state -> Text,
        exec_exit_code -> Nullable<Integer>,
        exec_state_unread -> Bool,
        exec_state_updated_at -> BigInt,
    }
}

diesel::table! {
    projects (id) {
        id -> Text,
        name -> Text,
        collapsed -> Bool,
        created_at -> BigInt,
        updated_at -> BigInt,
        resume_agent_sessions -> Bool,
        #[sql_name = "order"]
        order_index -> Integer,
    }
}

diesel::table! {
    workspaces (id) {
        id -> Text,
        project_id -> Text,
        name -> Text,
        path -> Text,
        branch -> Nullable<Text>,
        is_root -> Bool,
        collapsed -> Bool,
        created_at -> BigInt,
        updated_at -> BigInt,
    }
}

diesel::table! {
    managed_commands (id) {
        id -> Text,
        project_id -> Text,
        name -> Text,
        command -> Text,
        subfolder -> Nullable<Text>,
        restart_on_startup -> Bool,
        #[sql_name = "order"]
        order_index -> Integer,
        created_at -> BigInt,
        updated_at -> BigInt,
        source_kind -> Nullable<Text>,
        source_package_json_path -> Nullable<Text>,
        source_script_name -> Nullable<Text>,
        source_script_command_snapshot -> Nullable<Text>,
        package_manager -> Nullable<Text>,
    }
}

diesel::table! {
    command_instances (id) {
        id -> Text,
        command_id -> Text,
        workspace_id -> Text,
        last_state -> Text,
        scrollback -> Text,
        was_running_on_shutdown -> Bool,
        created_at -> BigInt,
        updated_at -> BigInt,
        last_exit_code -> Nullable<Integer>,
        ended_at -> Nullable<BigInt>,
        unread -> Bool,
        prev_scrollback -> Text,
        prev_exit_code -> Nullable<Integer>,
        prev_ended_at -> Nullable<BigInt>,
        prev_last_state -> Nullable<Text>,
    }
}

diesel::table! {
    agent_sessions (id) {
        id -> Text,
        terminal_id -> Text,
        workspace_id -> Nullable<Text>,
        agent_kind -> Text,
        external_session_id -> Text,
        cwd -> Text,
        state -> Text,
        transcript_path -> Nullable<Text>,
        metadata_json -> Text,
        started_at -> BigInt,
        ended_at -> Nullable<BigInt>,
        last_seen_at -> BigInt,
    }
}

diesel::joinable!(workspaces -> projects (project_id));
diesel::joinable!(terminals -> workspaces (workspace_id));
diesel::joinable!(managed_commands -> projects (project_id));
diesel::joinable!(command_instances -> managed_commands (command_id));
diesel::joinable!(command_instances -> workspaces (workspace_id));
diesel::joinable!(agent_sessions -> terminals (terminal_id));
diesel::joinable!(agent_sessions -> workspaces (workspace_id));

diesel::allow_tables_to_appear_in_same_query!(
    agent_sessions,
    command_instances,
    managed_commands,
    projects,
    terminals,
    workspaces,
);
