-- Schema v3: managed commands (services) — PRD-3, Phase 1.
--
-- A `managed_command` is a per-project TEMPLATE for a long-running service-style
-- command (e.g. `npm run dev`). A `command_instance` is the materialization of
-- one template for one workspace: a project with N templates and M workspaces
-- ends up with N*M instances, each carrying that workspace's run state, scrollback
-- history, and a shutdown snapshot flag. Templates and instances are the persistent
-- socle only — spawning a process, the runner state machine, and the UI all land
-- in later phases (this migration adds NO runner, NO materialization logic).
--
-- Provenance: a template MAY originate from a `package.json` script (the
-- `source_*` columns) or be hand-authored (all NULL). `package_manager` records
-- the detected manager (npm/pnpm/yarn/bun) when imported. These are pure metadata
-- here; the importer that fills them lands in a later phase.
--
-- Timestamps mirror the rest of the schema: epoch MILLISECONDS as INTEGER, set
-- explicitly by the backend on every write, with the portable julianday DEFAULT
-- as a safety net for any raw insert.

-- A per-project command template.
--
-- `command` is the literal command line to run (read-only execution in a later
-- phase). `subfolder` is an OPTIONAL path RELATIVE to the workspace folder where
-- the command runs (NULL = the workspace root). `restart_on_startup` is a SQLite
-- INTEGER 0/1 boolean (mapped to a Rust `bool`): when set, the runner relaunches
-- the instance at app start (later phase). `"order"` is the sidebar order within
-- the project (a SQL keyword, double-quoted; exposed to Rust as `order_index`).
--
-- `source_kind` is NULL for a hand-authored template, or `'package_json'` for one
-- imported from a package.json script (the only kind today; CHECK keeps it that
-- way). The other `source_*` columns record WHICH script and a SNAPSHOT of its
-- command at import time so a later drift between the file and the template is
-- detectable. `package_manager`, when set, is the detected manager.
--
-- `UNIQUE(project_id, name)` makes a template name unique within its project (two
-- projects may legitimately share a template name).
CREATE TABLE managed_commands (
    -- UUIDv7 generated by the backend (SQLite does not auto-generate it).
    id                            TEXT    NOT NULL PRIMARY KEY,
    project_id                    TEXT    NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name                          TEXT    NOT NULL,
    command                       TEXT    NOT NULL,
    -- Optional run subfolder, relative to the workspace path (NULL = root).
    subfolder                     TEXT,
    restart_on_startup            INTEGER NOT NULL DEFAULT 0 CHECK (restart_on_startup IN (0, 1)),
    "order"                       INTEGER NOT NULL DEFAULT 0,
    created_at                    INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    updated_at                    INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    -- Provenance metadata (all NULL for a hand-authored template).
    source_kind                   TEXT    CHECK (source_kind IS NULL OR source_kind IN ('package_json')),
    source_package_json_path      TEXT,
    source_script_name            TEXT,
    source_script_command_snapshot TEXT,
    package_manager               TEXT    CHECK (package_manager IS NULL OR package_manager IN ('npm', 'pnpm', 'yarn', 'bun')),
    -- A template name is unique within a project, never globally.
    UNIQUE (project_id, name)
);

-- Index the FK column for fast `list_templates(project_id)` scans.
CREATE INDEX idx_managed_commands_project ON managed_commands (project_id);

-- The materialization of one template for one workspace.
--
-- `last_state` is the last persisted run state of this instance, one of
-- idle|running|success|error (CHECK-enforced). It defaults to 'idle' (never run).
-- `scrollback` holds the serialized output history (bounded by the backend before
-- write, like terminals); it defaults to ''. `was_running_on_shutdown` is a 0/1
-- boolean snapshot the shutdown flow sets so the restore flow (later phase) knows
-- which instances to relaunch; it is reset to 0 after boot.
--
-- BOTH foreign keys ON DELETE CASCADE: deleting the template OR the workspace
-- removes the instance (an instance is meaningless without either parent).
-- `UNIQUE(command_id, workspace_id)` makes materialization idempotent — a template
-- has at most one instance per workspace.
CREATE TABLE command_instances (
    id                      TEXT    NOT NULL PRIMARY KEY,
    command_id              TEXT    NOT NULL REFERENCES managed_commands(id) ON DELETE CASCADE,
    workspace_id            TEXT    NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    last_state              TEXT    NOT NULL DEFAULT 'idle' CHECK (last_state IN ('idle', 'running', 'success', 'error')),
    scrollback              TEXT    NOT NULL DEFAULT '',
    was_running_on_shutdown INTEGER NOT NULL DEFAULT 0 CHECK (was_running_on_shutdown IN (0, 1)),
    created_at              INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    updated_at              INTEGER NOT NULL DEFAULT (CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)),
    -- One instance per (template, workspace): makes materialization idempotent.
    UNIQUE (command_id, workspace_id)
);

-- Index both FK columns for fast per-template and per-workspace listing.
CREATE INDEX idx_command_instances_command ON command_instances (command_id);
CREATE INDEX idx_command_instances_workspace ON command_instances (workspace_id);
