// @generated automatically by Diesel CLI — kept in sync by hand here because the
// project builds without the `diesel` CLI installed. It MUST stay consistent
// with `migrations/00000000000001_create_terminals/up.sql`; the test
// `db::tests::schema_matches_migration` round-trips every column to enforce that.
//
// Mapping notes:
// - `id` is a UUIDv7 stored as SQLite `TEXT PRIMARY KEY` → `Text` (generated by
//   the backend on insert; SQLite does not auto-generate it).
// - `order` is a SQL keyword; the SQL column is `"order"` and we expose it to
//   Rust as `order_index` via `#[sql_name]` so neither SQL nor Rust collides
//   with the keyword.
// - timestamps are epoch MILLISECONDS as `INTEGER` (SQLite has no native
//   datetime) → `BigInt` (i64). `created_at`/`updated_at` are NOT NULL;
//   `closed_at` is `Nullable<BigInt>` (NULL until the terminal is closed).

diesel::table! {
    terminals (id) {
        id -> Text,
        cwd -> Text,
        label -> Nullable<Text>,
        scrollback -> Text,
        status -> Text,
        #[sql_name = "order"]
        order_index -> Integer,
        created_at -> BigInt,
        updated_at -> BigInt,
        closed_at -> Nullable<BigInt>,
        last_active_at -> Nullable<BigInt>,
    }
}
